spring.application.name=ERP

spring.datasource.url=jdbc:postgresql://localhost:5432/erp
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=Y29tcGxldGVseS1yYW5kb20tc2VjdXJlLXNlY3JldC1mb3ItZXJwLWFwcC0zMnBsdXM=
jwt.expiration=86400000